Traceback (most recent call last):
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/Explorer.py", line 584, in start
    explorer = Explorer(config_id, appium_port, udid, logfile)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/Explorer.py", line 30, in __init__
    self.src_events, self.src_labels = Util.load_events(self.config.id, 'base_from')
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/Util.py", line 110, in load_events
    src_events = Util.run_source_test(fpath)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/Util.py", line 101, in run_source_test
    extractor = CraftdroidExtractor(file)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/test_attribute_extractor/test_attribute_extractor.py", line 23, in __init__
    self.driver = self.check_run_possible(self.app_package, caps)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/test_attribute_extractor/test_attribute_extractor.py", line 49, in check_run_possible
    driver = webdriver.Remote('http://localhost:4723/wd/hub', caps)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/venv/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 151, in __init__
    proxy
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/venv/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 227, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

